replicaCount: 1
image:
  repository: registry/comments-api
  tag: latest
  #pullPolicy: Always
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 8080


postgres:
  enabled: true
  image: postgres:15-alpine
  postgresqlDatabase: commentsdb
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  port: 5432
  persistence:
    enabled: true
    size: 1Gi


otelCollector:
  enabled: true
  image: otel/opentelemetry-collector-contrib:0.79.0


resources: {}


ingress:
  enabled: false