apiVersion: v1
kind: Service
metadata:
  name: {{ include "comments-api.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "comments-api.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http